### ISSUE TITLE
does not support go 1.7

### ISSUE THREAD

**Issue by nangong92t** [kitech/php-go#14]
does not support go 1.7

**Comment by kitech** [comment]
does go 1.7 has any problem?

**Comment by nangong92t** [comment]
yes, can not run

**Comment by kitech** [comment]
thanks, i will try.

**Comment by kitech** [comment]
confirmed.
should be hard to fix that, and i don't known why or how.

Thread 2 "php56" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff332e700 (LWP 14341)]
0x00007ffff33e99c4 in runtime.newobject () from ./hello.so

**Comment by nangong92t** [comment]
yes, the results of my gdb are the same, currently do not know why.

**Comment by kitech** [comment]
go build -gcflags="-newexport=0 -ssa=0"
still not use.

**Comment by kitech** [comment]
and i minimize entire project to only one file.go, still crash as that.
even can not run arrive func init().
