### ISSUE TITLE
php7中调用go函数时出现 segmentation fault (core dumped) 

### ISSUE THREAD

**Issue by x-i-ao-b-ai** [kitech/php-go#18]
```
var_dump(foo_hello3(1,"w",2.1));
```
报错位置
extension.c 330 行左右

printf("arg%d, type=%d\n", idx, Z_TYPE_PP(args[idx])); 这行有错误

**Comment by kitech** [comment]
thanks

问一下，是用php-fpm执行还是php命令行执行呢？

**Comment by x-i-ao-b-ai** [comment]
php 命令执行的 php -d extension=./hello.so -f examples/hello.php
我是 arch群的小白喵  你的库我总是用不了怎么办

**Comment by kitech** [comment]
啊，原来是你

**Comment by kitech** [comment]
可能是参数转换有问题。要不要换个参数试试，先看能不能跑通？

**Comment by x-i-ao-b-ai** [comment]
只要是带参数就吐核了

**Comment by kitech** [comment]
唉，又是php5/php7的不兼容问题。
