### ISSUE TITLE
执行两次太快导致的错误？？？？

### ISSUE THREAD

**Issue by xywf221** [kitech/php-go#34]
执行一次然后关闭然后快速的执行下一次奔溃
➜  php-go-test php -d extension=./examples.so main.php
[php -d extension=./examples.so main.php]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x10700efce]

goroutine 17 [running, locked to thread]:
github.com/kitech/php-go/phpgo.(*FuncEntry).IsGlobal(...)
	/Users/mac-mini/go/src/github.com/kitech/php-go/phpgo/extension.go:63
github.com/kitech/php-go/phpgo.on_phpgo_function_callback_p(0xffffffffffffffff, 0x106c1f0d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/mac-mini/go/src/github.com/kitech/php-go/phpgo/extension.go:492 +0xace
github.com/kitech/php-go/phpgo._cgoexpwrap_845d1fe97f7e_on_phpgo_function_callback_p(0xffffffffffffffff, 0x106c1f0d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/kitech/php-go/phpgo/_obj/_cgo_gotypes.go:424 +0xdb

**Comment by xywf221** [comment]
2018-05-10 18:28:02 extension.c(565): INFO: mapget: 0x0, -1=?-1

**Comment by hxslcc** [comment]
这个问题处理了么？
