### ISSUE TITLE
I got that error with example 

### ISSUE THREAD

**Issue by gokaybiz** [kitech/php-go#43]
`zend/typeconv.go:30:26: could not determine kind of name for C.IS_CONSTANT`
How can i fix this?

**Comment by RobertWang** [comment]
+1

**Comment by parsibox** [comment]
i have also this problem

**Comment by gokaybiz** [comment]
php-go is no longer maintained. 
https://github.com/l-vitaly/php-go/tree/master 
maybe you should try this fork.
