### ISSUE TITLE
Fail to make it 

### ISSUE THREAD

**Issue by hyper0x** [kitech/php-go#5]
Hi,

I ran `make` under the project's dir, and got:

```
$ make
go install ./zend
# github.com/hyper-carrot/php-go/zend
In file included from zend/szend.c:10:
In file included from /usr/local/Cellar/php56/5.6.22/include/php/Zend/zend_API.h:26:
In file included from /usr/local/Cellar/php56/5.6.22/include/php/Zend/zend_modules.h:25:
In file included from /usr/local/Cellar/php56/5.6.22/include/php/Zend/zend.h:51:
In file included from /usr/local/Cellar/php56/5.6.22/include/php/Zend/zend_config.h:1:
In file included from /usr/local/Cellar/php56/5.6.22/include/php/main/../main/php_config.h:2530:
/usr/include/sys/types.h:92:23: error: cannot combine with previous 'int' declaration specifier
zend/sztypes.h:5:23: note: expanded from macro 'uint'
make: *** [all] Error 2
```

I don't know what is the matter. My Env:

```
OS: OS X 10.11.5
Go version: 1.6.1
PHP version: 5.6.22 (install with homebrew)
```

**Comment by kitech** [comment]
When I try little change, that's compile error can be fixed.
But now golang(<=1.6) for OS X not support `-linkshared` parameter, 
so one can only use gozend, can not use phpgo.

**Comment by hyper-carrot** [comment]
OK, looking forward to improving. Would you provide the point in time?

**Comment by kitech** [comment]
Of couse.
I can compile zend and phpgo packages to .a on OS X. Next step don't known how link it.
I can just fix the first half of this bug now.

**Comment by kitech** [comment]
Another, I try the brew install php56, this package not contains embed library named like libphp5.so.
Maybe need a custom build php package for full feature.
Much work to do about OS X platform.

**Comment by hyper-carrot** [comment]
@kitech OK, Thank you.

**Comment by joostshao** [comment]
两个中国人...

**Comment by kitech** [comment]
@hyper-carrot Thank you too.

**Comment by joostshao** [comment]
OK了，谢谢
run gozend init... 4
run gozend init... 1
[phpgo] 2016/06/03 23:58:07 hello.go:77: run us init...
[phpgo] 2016/06/03 23:58:07 typeconv.go:92: ===  0
add func foo_hello at 0:0=0, 0x7fd5818fca10, atys=, rety=0
[phpgo] 2016/06/03 23:58:07 typeconv.go:92: ===  0
add func foo_hello2 at 0:1=1, 0x7fd5818fca20, atys=, rety=4
[phpgo] 2016/06/03 23:58:07 typeconv.go:92: === lsd 3
add func foo_hello3 at 0:2=2, 0x7fd5818fca30, atys=lsd, rety=0
[phpgo] 2016/06/03 23:58:07 typeconv.go:92: === v 1
add func foo_hello7 at 0:3=3, 0x7fd5818fca40, atys=v, rety=0
[phpgo] 2016/06/03 23:58:07 typeconv.go:92: === m 1
add func foo_hello8 at 0:4=4, 0x7fd5818fca50, atys=m, rety=0
[phpgo] 2016/06/03 23:58:07 hello.go:13: NewPGDemo...
[phpgo] 2016/06/03 23:58:07 hello.go:97: method fn: 0x7fd58182ee00 func() int 0x7fd58182d970
[phpgo] 2016/06/03 23:58:07 typeconv.go:92: ===  0
add mth PGDemo::__construct at 1:0=5, 0x7fd5818fca60, atys=, rety=9
[phpgo] 2016/06/03 23:58:07 typeconv.go:92: === p 1
add mth PGDemo::Hello1 at 1:1=6, 0x7fd5818fca70, atys=p, rety=4
[phpgo] 2016/06/03 23:58:07 typeconv.go:92: === p 1
add mth PGDemo::Hello2 at 1:2=7, 0x7fd5818fca80, atys=p, rety=0
[phpgo] 2016/06/03 23:58:07 typeconv.go:92: === p 1
add mth PGDemo::Hello3 at 1:3=8, 0x7fd5818fca90, atys=p, rety=0
[phpgo] 2016/06/03 23:58:07 typeconv.go:92: === p 1
add mth PGDemo::Hello4 at 1:4=9, 0x7fd5818fcaa0, atys=p, rety=0
[phpgo] 2016/06/03 23:58:07 typeconv.go:92: === p 1
add mth PGDemo::Hello5 at 1:5=10, 0x7fd5818fcab0, atys=p, rety=0
[phpgo] 2016/06/03 23:58:07 typeconv.go:92: === p 1
add mth PGDemo::Hello6 at 1:6=11, 0x7fd5818fcac0, atys=p, rety=0
add class: PGDemo 1
[phpgo] 2016/06/03 23:58:07 typeconv.go:92: === l 1
add func GoExit at 0:5=12, 0x7fd5818fcad0, atys=l, rety=0
[phpgo] 2016/06/03 23:58:07 typeconv.go:92: === a 1
add func GoGo at 0:6=13, 0x7fd5818fcae0, atys=a, rety=0
[phpgo] 2016/06/03 23:58:07 typeconv.go:92: ===  0
add func GoPanic at 0:7=14, 0x7fd5818fcaf0, atys=, rety=0
[phpgo] 2016/06/03 23:58:07 typeconv.go:92: ===  0
add func GoRecover at 0:8=15, 0x7fd5818fcb00, atys=, rety=0
[phpgo] 2016/06/03 23:58:07 typeconv.go:92: === la 2
add func GoPrintln at 0:9=16, 0x7fd5818fcb10, atys=la, rety=0
mod=0x7fd581c7d8a0
module_startup 1 51
request_startup 1 51
function handler called.0, this=0x7fd582613140, atys=
parse params: 0
[phpgo] 2016/06/03 23:58:07 extension.go:413: go callback called: 0 0x7fd582613140 &{global foo_hello 0x7fd58182dc90 false}
[phpgo] 2016/06/03 23:58:07 extension.go:414: go callback called: [<nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil>]
[phpgo] 2016/06/03 23:58:07 hello.go:44: ext user func called
[phpgo] 2016/06/03 23:58:07 extension.go:435: meta call ret: [] <nil>
inout ret:(nil)
convert ret: (nil), type: 0(void)
PHP Warning:  unrecognized return value: 0. in /mnt/data/gocode/src/github.com/kitech/php-go/examples/hello.php on line 4
function handler called.5, this=0x7fd582613140, atys=
parse params: 0
[phpgo] 2016/06/03 23:58:07 extension.go:413: go callback called: 5 0x7fd582613140 &{PGDemo __construct 0x7fd58182d970 true}
[phpgo] 2016/06/03 23:58:07 extension.go:414: go callback called: [<nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil>]
[phpgo] 2016/06/03 23:58:07 hello.go:13: NewPGDemo...
[phpgo] 2016/06/03 23:58:07 extension.go:435: meta call ret: [<*main.PGDemo Value>] 0xc820010960
inout ret:0xc820010960
convert ret: 0xc820010960, type: 9(pointer)
function handler called.6, this=0x7fd582613140, atys=p
param count error: 1
PHP Warning:  Wrong parameter count for PGDemo::Hello1() in /mnt/data/gocode/src/github.com/kitech/php-go/examples/hello.php on line 7
[phpgo] 2016/06/03 23:58:07 extension.go:413: go callback called: 6 0x7fd582613140 &{PGDemo Hello1 0x7fd58182da90 false}
[phpgo] 2016/06/03 23:58:07 extension.go:414: go callback called: [<nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil>]
[phpgo] 2016/06/03 23:58:07 hello.go:19: called in go scope, hello1 method 30870
[phpgo] 2016/06/03 23:58:07 extension.go:435: meta call ret: [<int Value>] 0xc820010a40
inout ret:0xc820010a40
convert ret: 0xc820010a40, type: 4(long)
int(30870)
request_shutdown 1 51

**Comment by joostshao** [comment]
编译速度很快

**Comment by kitech** [comment]
好棒，只是输出调试信息太多了

**Comment by hyper-carrot** [comment]
@kitech @joostshao English discussions conducive to international collaboration. It's a lesson for open source project on Github.

**Comment by kitech** [comment]
since go 1.8 has full support buildmode=c-shared for MacOS, 

with some test and looks fine. 

think as fixed if no more report.

**Comment by septianw** [comment]
It's been years ago, please, somebody close this issue.
