### ISSUE TITLE
还是新开一个issue吧，为什么编译出来的动态链接库文件那么大？

### ISSUE THREAD

**Issue by joostshao** [kitech/php-go#6]
3.2M -rw-rw-r-- 1 ubt ubt 3.2M  6月  5 07:14 hello.so

但是一般的原生扩展都很小，即便是swoole，才2MB不到。

1.8M -rwxr-xr-x 1 root root 1.8M  5月 25 00:00 swoole.so*

**Comment by joostshao** [comment]
ps： 动态链接文件应该是整个都会被加载到内存里面的，应该是在必要的解压之后

**Comment by kitech** [comment]
golang语言的特点，就是编译出来的文件比较大

**Comment by joostshao** [comment]
别忽悠我，你是整个.a文件都rapper进来了。。。

**Comment by kitech** [comment]
可是那是用go build编译出来的，做不了什么优化了。再strip一下估计好点吧。

**Comment by nangong92t** [comment]
这并不是一个问题

**Comment by septianw** [comment]
Bigger file is a risk we took of using go to write PHP extension. it's been years ago, please somebody close this issue.
